#let terms = (
  (slug: "term-job", title: [Job], body: [A retained PostgreSQL record of one versioned worker input, its scheduling and accounting, and its committed outcome. Its integer identity is distinct from the caller submission key.]),
  (slug: "term-worker", title: [Worker], body: [A deployed typed definition retaining worker identity, version, input/output/optional error codecs, queue, handler and execution policies.]),
  (slug: "term-codec", title: [Codec], body: [A versioned typed JSON encoder and decoder. Encoder refusal is a value; semantic compatibility across versions belongs to the application.]),
  (slug: "term-installation", title: [Installation], body: [One Grind schema in a PostgreSQL database. Database privileges and schema separation provide isolation; the client identity token only guards accidental handle reuse.]),
  (slug: "term-submission-key", title: [Submission key], body: [A caller-supplied or generated string identifying an admission command. Retrying the same retained request and key converges on its durable receipt.]),
  (slug: "term-admission-receipt", title: [Admission receipt], body: [A durable record of a submission command fingerprint and its original Inserted, Existing or Rescheduled decision. Its lifetime ends when the referenced job is pruned.]),
  (slug: "term-uniqueness-domain", title: [Uniqueness domain], body: [A matching namespace including installation, worker identity/version, key contract and optional queue. Incoming state and time filters select candidates inside it.]),
  (slug: "term-key-contract", title: [Key contract], body: [Full encoded input with its input codec version, or a named/versioned typed projection. Only jobs admitted with matching retained material participate.]),
  (slug: "term-claim", title: [Claim], body: [Database authority to execute an eligible job while its executing state, attempt identity, epoch, owner and lease remain current.]),
  (slug: "term-attempt-ordinal", title: [Attempt ordinal], body: [The retry-budget counter. Snooze and authorized abandonment replay refund it, so it can repeat and cannot fence ownership.]),
  (slug: "term-attempt-fence", title: [Attempt fence], body: [The job, attempt identity, epoch, owner and live lease checked atomically before execution writes. Same-owner renewal preserves the fence; takeover invalidates it.]),
  (slug: "term-lease", title: [Lease], body: [A database-time expiry for a claim. An expired lease grants no new acknowledgement or renewal write, even when the old process is alive.]),
  (slug: "term-acknowledgement", title: [Acknowledgement], body: [A retained proposal for a claimed attempt and a stable command identity. Its receipt records the actual committed disposition, which can differ from the proposal.]),
  (slug: "term-uncertain-effect", title: [Uncertain effect], body: [Evidence that an attempt may have performed an effect whose outcome is unknown. It is not evidence of failure or permission to retry.]),
  (slug: "term-cancellation-intent", title: [Cancellation intent], body: [A committed request to stop further work. It asks an executing handler to stop cooperatively and forbids replay of an uncertain job. It cannot undo an effect and does not prove that the handler stopped.]),
  (slug: "term-operator-resolution", title: [Operator resolution], body: [An attributed, idempotent command confirming success/business failure or authorizing replay of an uncertain job after application investigation.]),
  (slug: "term-borrowed-transaction", title: [Borrowed transaction], body: [A caller-owned open READ COMMITTED PostgreSQL transaction used for admission or operator-resolution statements without Grind issuing BEGIN or COMMIT.]),
  (slug: "term-available-time", title: [Available time], body: [The absolute database availability of a job. Relative admission delays are resolved using the database clock; recurring timezone schedules are a separate capability.]),
  (slug: "term-correlation", title: [Correlation], body: [Application-supplied or generated tracing context. It is neither the admission idempotency key nor an authorization credential.]),
  (slug: "term-observation", title: [Observation], body: [A best-effort typed Sinal event. Lifecycle observations follow evidence of a committed transition; diagnostic observations describe runtime behavior.]),
  (slug: "term-capacity", title: [Capacity], body: [The per-consumer local slot budget occupied by running attempts and attempts with pending acknowledgements. It is not a cluster-wide execution limit.]),
  (slug: "term-retention", title: [Retention], body: [The period after terminal finished_at during which jobs and their dependent receipts remain recoverable. Uncertain jobs have no finished_at and are excluded.]),
)
